### ISSUE TITLE
Error on missing object property

### ISSUE THREAD

**Issue by juvid** [wol-soft/php-micro-template#5]
Hello!

If I assign an object (e.g. a Laravel Eloquent model) as a variable and in the template I reference to a non-existent property of the object, the renderer throws an error instead of the UndefinedSymbolException, so I don't know, which property is missing.

TypeError(code: 0): array_key_exists(): Argument # 2 ($array) must be of type array, App\\Models\\Product given at /var/www/vendor/wol-soft/php-micro-template/src/Render.php:243

Thank You

**Comment by wol-soft** [comment]
Hi @juvid,

are you trying to access public properties of the object? That would be a feature which is currently not supported. The library currently only supports calling methods on assigned objects.

Cheers

**Comment by juvid** [comment]
Hi,
yes, I am trying to access a public property with value null (isset() = false). If it exists and not null it works perfect, thanks to ArrayAccess implementation. Only the array_key_exists function throws a type error in the previous case.

**Comment by wol-soft** [comment]
Hi,

I've added a patch for the issue in 1.7.0 as well as the possibility to directly access public object properties from the template.

Cheers.

**Comment by juvid** [comment]
Thank you for the fast response, works great.
