### ISSUE TITLE
function with parameters issue...

### ISSUE THREAD

**Issue by scramatte** [wol-soft/php-micro-template#7]
Hello,

I'm using functions with your template renderer, but I've got an issue with parameters.
I'm unable to pass string or number as parameter directly 

![image](https://github.com/wol-soft/php-micro-template/assets/188766/c61c88fd-4e96-44bb-868a-a851723fa4b7)

```php
 $template = "F{{format.date('Y')}}-{{format.sequence(8)}}";
````

```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

use PHPMicroTemplate\Render;
use Carbon\Carbon;

class TemplateFormat {

   public function sequence($digits=6) {
      return sprintf('%0'.$digits.'d', 7);
   }

   public function date($format='Y') {
      return Carbon::now()->format($format);
   }

}

class Template extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'template:render';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'replace variable into template';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {

        $render = new Render();
        $template = "F{{format.date('Y')}}-{{format.sequence(8)}}";

        $result = $render->renderTemplateString(
            $template,
            [
               'format' => new TemplateFormat,
            ]
        );

        echo  $result . PHP_EOL;
        return Command::SUCCESS;
   }   
}
``` 

Any idea what I'm doing wrong?

Regards

**Comment by wol-soft** [comment]
Hi,

parsing parameter arguments like strings, integers, floats, arrays etc. is not supported by the library. Only template variables and function calls will be resolved (compare: https://github.com/wol-soft/php-micro-template#replacement-of-variables)

**Comment by scramatte** [comment]
Does it possible to implement it?
We can sponsor the job.

**Comment by wol-soft** [comment]
Although the library should stay minimalistic this feature with a limited scope seems like a reasonable addition.

I've implemented the feature in https://github.com/wol-soft/php-micro-template/commit/93dc8de0762eb46201f5ddce7a98db22576d84b8 and tagged in version [1.8.0](https://github.com/wol-soft/php-micro-template/releases/tag/1.8.0)

The rendering now supports parsing of integer numbers, strings in single quotes and booleans (true, false)

**Comment by scramatte** [comment]
Thank you very much
