### ISSUE TITLE
custom start and end marker

### ISSUE THREAD

**Issue by rjjrbatarao** [wol-soft/php-micro-template#9]
thank you for this library, one thing i need to be able to customize the markers {% %} and the {{ }}
i was trying to replicate a template engine which uses $( and ) as start and end markers for variables, conditional and loop I dont want to edit the library but if its the case then theres no other choice

**Comment by wol-soft** [comment]
Hi, I don't think this fits the style of the library to be as small and simple as possible so I will not add configuration options for the syntax. Thanks for the request anyways.
